### ISSUE TITLE
DEPRECATION: The `initialize` method for Application initializer 'route-layers' should take only one argument 

### ISSUE THREAD

**Issue by osxi** [dollarshaveclub/ember-route-layers#2]
From the JS console:

```
DEPRECATION: The `initialize` method for Application initializer 'route-layers' should take only one argument - `App`, an instance of an `Application`. [deprecation id: ember-application.app-initializer-initialize-arguments] See http://emberjs.com/deprecations/v2.x/#toc_initializer-arity for more details.
```

**Comment by arjansingh** [comment]
@osxi Which version of Ember are you seeing this for? We need to make sure #3 is updated with the proper Semver.

**Comment by osxi** [comment]
The deprecation was added in 2.1 (http://emberjs.com/deprecations/v2.x/) but I first saw it on 2.2.0.

**Comment by arjansingh** [comment]
ok @pwfisher should this be `v2.1.0`?

**Comment by pwfisher** [comment]
Sure

**Comment by arjansingh** [comment]
@osxi update the PR `package.json` to `2.1.0` please and we will accept and publish.

**Comment by osxi** [comment]
Added some stuff to package.json:
  - I updated the `version` in package.json to reflect 2.2.0 since this is the latest release version of Ember
  - Updated `author` as per @pwfisher's other packages here on GitHub
  - Updated `engines`to reflect Node >= 0.12.0

I recommend also adding a 2.2.0 tag to the repo so people can navigate through changes for troubleshooting purposes.

Thanks for all the hard work!
