### ISSUE TITLE
Publish 2.2.0 to NPM

### ISSUE THREAD

**Issue by osxi** [dollarshaveclub/ember-route-layers#4]
$ npm install ember-route-layers@2.2.0
npm ERR! Darwin 15.0.0
npm ERR! argv "/Users/zach/.nvm/versions/node/v5.4.1/bin/node" "/Users/zach/.nvm/versions/node/v5.4.1/bin/npm" "install" "ember-route-layers@2.2.0"
npm ERR! node v5.4.1
npm ERR! npm  v3.3.12

npm ERR! No compatible version found: ember-route-layers@2.2.0
npm ERR! Valid install targets:
npm ERR! 2.0.0, 1.0.4, 1.0.3, 1.0.2, 1.0.1, 1.0.0
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/zach/code/app/frontend/npm-debug.log

**Comment by arjansingh** [comment]
Sorry forgot we don't have travis hooked up on this repo.

**Comment by arjansingh** [comment]
@osxi done

**Comment by osxi** [comment]
@arjansingh awesome!
